### ISSUE TITLE
Correção do grid dos repositórios

### ISSUE THREAD

**Issue by EdiJunior88** [brunois10/github_perfil#1]
Fala Bruno tranquilo? seu projeto ficou muito massa mas tem um erro na visualização em que o grid dos repositórios vaza do container como mostra na imagem abaixo:

![Github-Perfil](https://github.com/brunois10/github_perfil/assets/13875907/0a4ebb48-22c5-4a4c-9ee3-b24208fbb424)

Verificando a classe **.container** se tirar o **max-width** a **ul** não vaza do **container**

`
.container {
    max-width: 960px;
    width: 100%;
    margin: 0 auto;
}
`

![Github-Perfil-2](https://github.com/brunois10/github_perfil/assets/13875907/509486e3-bae5-4c4b-bbb7-cabaf9739460)

Se possível coloca o **grid para apresentar apenas 2 colunas** até 1300px e **aumenta o gap entre as colunas** para ficar melhor na visualização. A minha tela aqui é 1366 x 768, se for acima disso é bom colocar o grid para 3 colunas ou mais (não é uma regra mas distribui melhor a visualização para telas "largas")

**Comment by brunois10** [comment]
Boa noite, tudo tranquilo! Agradeço o feedback, havia testado a responsividade anteriormente e não havia encontrado nenhum vazamento do container. Porém, realizei a alteração conforme sua sugestão.

Coloquei o width:90% e tirei o max-width. Isso soluciona também qualquer problema em outra responsividade.
att
________________________________
De: Edivaldo Junior ***@***.***>
Enviado: quarta-feira, 20 de dezembro de 2023 11:57
Para: brunois10/github_perfil ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: [brunois10/github_perfil] Correção do grid dos repositórios (Issue #1)


Fala Bruno tranquilo? seu projeto ficou muito massa mas tem um erro na visualização em que o grid dos repositórios vaza do container como mostra na imagem abaixo:

Github-Perfil.png (view on web)<https://github.com/brunois10/github_perfil/assets/13875907/0a4ebb48-22c5-4a4c-9ee3-b24208fbb424>

Verificando a classe .container se tirar o max-width a ul não vaza do container

.container { max-width: 960px; width: 100%; margin: 0 auto; }

Github-Perfil-2.png (view on web)<https://github.com/brunois10/github_perfil/assets/13875907/509486e3-bae5-4c4b-bbb7-cabaf9739460>

Se possível coloca o grid para apresentar apenas 2 colunas até 1300px e aumenta o gap entre as colunas para ficar melhor na visualização. A minha tela aqui é 1366 x 768, se for acima disso é bom colocar o grid para 3 colunas ou mais (não é uma regra mas distribui melhor a visualização para telas "largas")
